body:
  - type: markdown
    attributes:
      value: |
        ## We're here for you as a community 
  - type: markdown
    attributes:
      value: |
        Before creating a discussion just know that **your discussion will be public** and will be viewed by public volunteers so **do not include any senstive information**.
  - type: textarea
    id: conversation
    attributes:
      label: Write your question
      description: "Write your question or problem below. Ensure you have read and adhere to our [Code of Conduct](https://github.com/RyanLua/WebEdit/blob/main/CODE_OF_CONDUCT.md)."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Remember to mark an [answer as "solved"](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#marking-a-comment-as-an-answer) to help others with similar questions.
